image: docker:latest
services:
  - docker:dind

stages:
  - build
  - release
  - deploy

variables:
  COMMIT_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $COMMIT_IMAGE .
    - docker push $COMMIT_IMAGE

release:
  stage: release
  script:
    - docker pull $COMMIT_IMAGE
    - docker tag $COMMIT_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - master
  when: manual

  before_script:
    - apk update && apk add openssh-client sshpass

  script:
  - sshpass -p $DEPLOYMENT_SERVER_PASS ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no git@svia.nl "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com && cd /opt/docker/containers/nsvki.nl/ && docker-compose pull app && docker-compose up -d app"

  environment:
    name: production
    url: https://nsvki.nl/


# vim: ts=2 sw=2
